#!/bin/zsh

set -e

# Ask for the administrator password upfront
sudo -v

echo "Installing chezmoi and applying dotfiles ..."
brew bundle --file=- <<EOF
    brew 'chezmoi'
EOF
if [ ! -f "$HOME/.config/chezmoi/chezmoi.toml" ]; then
  chezmoi init --apply --verbose https://github.com/sanderginn/dotfiles.git
  # uncomment if there are secrets in the config
  # chmod 0600 "$HOME/.config/chezmoi/chezmoi.toml"
fi

echo "Running your customizations..."

if [ -f "$HOME/Brewfile" ]; then
  echo "Installing tools and apps from Brewfile ..."
  if brew bundle --file="$HOME/Brewfile"; then
    echo "All items in Brewfile were installed successfully."
  else
    echo "Some items in Brewfile were not installed successfully."
  fi
fi

if [ -f "$HOME/.functions" ]; then
  # shellcheck source=/dev/null
  echo "Setting shell functions..."
  . "$HOME/.functions"
fi

if [ -f "$HOME/.aliases" ]; then
  # shellcheck source=/dev/null
  echo "Setting shell aliases..."
  . "$HOME/.aliases"
fi

if [ -f "$HOME/.zshrc" ]; then
  # shellcheck source=/dev/null
  echo "Setting zsh functions..."
  . "$HOME/.zshrc"
fi

if [ -f "$HOME/.macos_config" ]; then
  # shellcheck source=/dev/null
  . "$HOME/.macos_config"
fi

# Kill terminal to apply changes
pkill -a Terminal